import type { Metadata } from "next";
import {Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight:["400","700"],
  display:"swap",
});


export const metadata: Metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="bg-white min-h-screen flex flex-col">
        <Header />
         <main className="container mx-auto px-4 py-8 text-black .flex-grow">
          {children}
        </main>
       <Footer />
      </body>
    </html>
  );
}
